### ISSUE TITLE
Don't know how to install

### ISSUE THREAD

**Issue by alejandrouus** [ScottFerg56/GFXFontEditor#3]
Hello, 

It looks very promising, but I don't know how can I run the program...

Thank you, 

Alejandro

**Comment by ScottFerg56** [comment]
Under 'Releases' is a Windows .MSI (install) file. Double click that file, or right-click and select 'Install', to install the program. Note the requirements in the README.

**Comment by alejandrouus** [comment]
Thank  you for your quick response. I'm not used to GitHub. I just downlad the -ZIP of the repository, but I didn't find the .MSI file. 

![capture](https://github.com/user-attachments/assets/950505d4-7afb-4fbe-a5f3-8f479f22c70d)
